apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: cap
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb